//
//  SFDictionary.h
//  SFramework
//
//  Created by Sattar Falahati (SFramework) on 13/04/16.
//  Copyright © 2016 Sattar Falahati (SFramework). All rights reserved.
//

#import <Foundation/Foundation.h>

@interface NSDictionary (SFDictionary)

- (id)safeValueForKey:(NSString *)key;

/**
 *  Returns a random key in the dictionary. The random index is generated by arc4random(). 
 *  @return A random key in the dictionary.
 */
- (id)getRandomKey;

/**
 *  Creates a string of the JSON representation of the dictionary.
 *
 *  @return An NSString containing the JSON representation of the dictionary.
 */
- (NSString *)createJSONString;


@end
